<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: io/altessa/type/v1/file_ref.proto

namespace GPBMetadata\Io\Altessa\Type\V1;

class FileRef
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\FieldBehavior::initOnce();
        $pool->internalAddGeneratedFile(
            '
ø
!io/altessa/type/v1/file_ref.protoio.altessa.type.v1"á
FileRef
url (	BàARurl
id (	BàARid@
metadata (2$.io.altessa.type.v1.FileRef.MetadataRmetadataç
Metadata
	mime_type (	RmimeType

size_bytes (R	sizeBytes
filename (	RfilenameH
custom (20.io.altessa.type.v1.FileRef.Metadata.CustomEntryRcustom9
CustomEntry
key (	Rkey
value (	Rvalue:8BS
io.altessa.type.v1PZ;github.com/altessa-s/proto-gen-go/io/altessa/type/v1;typev1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

